CREATE DATABASE IF NOT EXISTS registro_db;
USE registro_db;

CREATE TABLE registros(
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  telefono VARCHAR(20),
  codigo_qr VARCHAR(255) UNIQUE,
  usado BOOLEAN DEFAULT FALSE,
  fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)